import React from "react"

export default function DarRatePeshPatra() {
  return (
    <div>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
      <p>DarRatePeshPatra</p>
    </div>
  )
}
