export const users = [
    {
        key: "1",
        name: "Tony Reichert",
        role: "user",
        status: "Active",
    },
    {
        key: "2",
        name: "Zoey Lang",
        role: "user",
        status: "Paused",
    },
    {
        key: "3",
        name: "Jane Fisher",
        role: "admin",
        status: "Active",
    },
    {
        key: "4",
        name: "William Howard",
        role: "user",
        status: "Vacation",
    },
    {
        key: "5",
        name: "Emily Collins",
        role: "admin",
        status: "Active",
    },
    {
        key: "6",
        name: "Brian Kim",
        role: "user",
        status: "Active",
    },
    {
        key: "7",
        name: "Laura Thompson",
        role: "admin",
        status: "Active",
    },
    {
        key: "8",
        name: "Michael Stevens",
        role: "admin",
        status: "Paused",
    },
    {
        key: "9",
        name: "Sophia Nguyen",
        role: "admin",
        status: "Active",
    },
    {
        key: "10",
        name: "James Wilson",
        role: "user",
        status: "Vacation",
    },
    {
        key: "11",
        name: "Ava Johnson",
        role: "user",
        status: "Active",
    },
    {
        key: "12",
        name: "Isabella Smith",
        role: "user",
        status: "Active",
    },
    {
        key: "13",
        name: "Oliver Brown",
        role: "user",
        status: "Paused",
    },
    {
        key: "14",
        name: "Lucas Jones",
        role: "user",
        status: "Active",
    },
    {
        key: "15",
        name: "Grace Davis",
        role: "user",
        status: "Active",
    },
    {
        key: "16",
        name: "Elijah Garcia",
        role: "user",
        status: "Active",
    },
    {
        key: "17",
        name: "Emma Martinez",
        role: "admin",
        status: "Vacation",
    },
    {
        key: "18",
        name: "user",
        role: "Operations Manager",
        status: "Active",
    },
    {
        key: "19",
        name: "Mia Hernandez",
        role: "user",
        status: "Paused",
    },
    {
        key: "20",
        name: "Daniel Lewis",
        role: "user",
        status: "Active",
    },
    {
        key: "21",
        name: "Amelia Clark",
        role: "user",
        status: "Active",
    },
    {
        key: "22",
        name: "Jackson Walker",
        role: "user",
        status: "Active",
    },
    {
        key: "23",
        name: "Henry Hall",
        role: "user",
        status: "Active",
    },
    {
        key: "24",
        name: "admin",
        role: "PR Specialist",
        status: "Paused",
    },
    {
        key: "25",
        name: "Liam King",
        role: "user",
        status: "Active",
    },
];
